# -*- coding: utf-8 -*-
"""app.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cszmQKxn4TqosROE2KD2MjpPlDrbylgr
"""

import streamlit as st
import pandas as pd
import pdfplumber
from io import BytesIO
import xlsxwriter
from datetime import datetime

st.set_page_config(page_title="Retenciones SRI 2025", layout="wide")

st.title("📊 Generador de Retenciones SRI - Bitghun")

st.write("Sube los comprobantes en PDF y el sistema generará el Excel automáticamente.")

uploaded_files = st.file_uploader(
    "Subir comprobantes PDF",
    type="pdf",
    accept_multiple_files=True
)

columnas = [
"FECHA",
"IFIS",
"N FACTURA",
"RUC",
"DOC IFIS",
"AUTORIZACION",
"NO OBJETO",
"EXCENTO IVA",
"BASE 0%",
"BASE 15%",
"PROPINA",
"IVA",
"TOTAL",
"N° RETENCION",
"0% R.FTE",
"RETE 10%",
"RETE 100%",
"2% R.FTE",
"TOTAL RETENCION",
"valor retenido"
]

data = []

def extraer_datos_pdf(pdf_file):

    texto = ""

    with pdfplumber.open(pdf_file) as pdf:
        for page in pdf.pages:
            texto += page.extract_text()

    # Aquí puedes mejorar la extracción según el formato del comprobante
    fecha = datetime.today().strftime("%Y-%m-%d")

    fila = {
        "FECHA": fecha,
        "IFIS": "",
        "N FACTURA": "",
        "RUC": "",
        "DOC IFIS": "",
        "AUTORIZACION": "",
        "NO OBJETO": 0,
        "EXCENTO IVA": 0,
        "BASE 0%": 0,
        "BASE 15%": 0,
        "PROPINA": 0,
        "IVA": 0,
        "TOTAL": 0,
        "N° RETENCION": "",
        "0% R.FTE": 0,
        "RETE 10%": 0,
        "RETE 100%": 0,
        "2% R.FTE": 0,
        "TOTAL RETENCION": 0,
        "valor retenido": 0
    }

    return fila


if uploaded_files:

    for file in uploaded_files:
        fila = extraer_datos_pdf(file)
        data.append(fila)

    df = pd.DataFrame(data, columns=columnas)

    st.dataframe(df)

    output = BytesIO()

    with pd.ExcelWriter(output, engine='xlsxwriter') as writer:

        df.to_excel(writer, sheet_name='Retenciones', startrow=1, index=False)

        workbook = writer.book
        worksheet = writer.sheets['Retenciones']

        formato_header = workbook.add_format({
            'bold': True,
            'align': 'center',
            'valign': 'vcenter',
            'border':1,
            'bg_color': '#FFFF00'
        })

        formato_ret = workbook.add_format({
            'bold': True,
            'align': 'center',
            'border':1,
            'bg_color': '#00B0F0'
        })

        formato_total = workbook.add_format({
            'bold': True,
            'border':1,
            'bg_color': '#FFFF00'
        })

        for col_num, col_name in enumerate(columnas):

            if col_num >= 14:
                worksheet.write(0, col_num, col_name, formato_ret)
            else:
                worksheet.write(0, col_num, col_name, formato_header)

        filas = len(df) + 2

        worksheet.write(filas,0,"TOTAL",formato_total)

        for i in range(6,20):
            col_letter = chr(65+i)
            formula = f"=SUM({col_letter}2:{col_letter}{filas})"
            worksheet.write_formula(filas,i,formula,formato_total)

        worksheet.set_column(0,20,18)

    output.seek(0)

    st.download_button(
        label="📥 Descargar Excel",
        data=output,
        file_name="retenciones_sri_2025.xlsx",
        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    )